
// This file has been generated by the GUI designer. Do not modify.
namespace GTK_Demo_Client
{
	public partial class GameWindow
	{
		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget GTK_Demo_Client.GameWindow
			this.Name = "GTK_Demo_Client.GameWindow";
			this.Title = global::Mono.Unix.Catalog.GetString("GameWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show();
		}
	}
}
