
// This file has been generated by the GUI designer. Do not modify.
namespace GTK_Demo_Client
{
	public partial class PopupWindow
	{
		private global::Gtk.Frame frame1;

		private global::Gtk.Alignment GtkAlignment;

		private global::Gtk.Fixed fixed1;

		private global::Gtk.Label Message;

		private global::Gtk.Button button1;

		private global::Gtk.Label GtkLabel1;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget GTK_Demo_Client.PopupWindow
			this.Name = "GTK_Demo_Client.PopupWindow";
			this.Title = global::Mono.Unix.Catalog.GetString("PopupWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child GTK_Demo_Client.PopupWindow.Gtk.Container+ContainerChild
			this.frame1 = new global::Gtk.Frame();
			this.frame1.Name = "frame1";
			this.frame1.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame1.Gtk.Container+ContainerChild
			this.GtkAlignment = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
			this.GtkAlignment.Name = "GtkAlignment";
			this.GtkAlignment.LeftPadding = ((uint)(12));
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			this.fixed1 = new global::Gtk.Fixed();
			this.fixed1.Name = "fixed1";
			this.fixed1.HasWindow = false;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.Message = new global::Gtk.Label();
			this.Message.Name = "Message";
			this.fixed1.Add(this.Message);
			global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.Message]));
			w1.X = 45;
			w1.Y = 52;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.button1 = new global::Gtk.Button();
			this.button1.WidthRequest = 100;
			this.button1.CanFocus = true;
			this.button1.Name = "button1";
			this.button1.UseUnderline = true;
			this.button1.Label = global::Mono.Unix.Catalog.GetString("확인");
			this.fixed1.Add(this.button1);
			global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.button1]));
			w2.X = 90;
			w2.Y = 90;
			this.GtkAlignment.Add(this.fixed1);
			this.frame1.Add(this.GtkAlignment);
			this.GtkLabel1 = new global::Gtk.Label();
			this.GtkLabel1.Name = "GtkLabel1";
			this.GtkLabel1.LabelProp = global::Mono.Unix.Catalog.GetString("<b>Popup</b>");
			this.GtkLabel1.UseMarkup = true;
			this.frame1.LabelWidget = this.GtkLabel1;
			this.Add(this.frame1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 308;
			this.DefaultHeight = 162;
			this.Show();
			this.button1.Clicked += new global::System.EventHandler(this.clicked);
		}
	}
}
